// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcsldifqghjaxsehutgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjc2xkaWZxZ2hqYXhzZWh1dGd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTE5NzcsImV4cCI6MjA2NjcyNzk3N30.ofYZ8kkriBKQ85kNW3xu9PR8dXc4LVECeeTt_fm4Lrw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);